### ISSUE TITLE
mtnstim Tracking Issue for GitHub

### ISSUE THREAD

**Issue by mtnstim** [githubteacher/everyone-june-2016#50]
## My GitHub Flow:

**Let's get started!**
- [x] Make a branch
- [x] Commit changes on my branch
- [x] Open a pull request
- [ ] Collaborate and make more changes (commits)
- [ ] Merge my branch into master branch
